### ISSUE TITLE
Version 0.3.24 conflicts with postCSS

### ISSUE THREAD

**Issue by SGAMERyu** [Tahul/pinceau#11]
It seems to conflict with PostCSS at build time because postCSS parses style with CSS functions, causing it to fail to parse and thus fail to compile

I'm just going to print out the code that I passed into postCSS

```
// postcss code
css({
    '.pi-btn': {
      width: '100px'
    }
})


✓ 3 modules transformed.
[vite:css] [postcss] C:/Users/qixiyu/Desktop/pinceau-vue/src/components/button/button.vue?vue&type=style&index=0&lang.postcss:3:1: Unknown word
file: C:/Users/qixiyu/Desktop/pinceau-vue/src/components/button/button.vue?vue&type=style&index=0&lang.postcss:3:1
error during build:
CssSyntaxError: [postcss] C:/Users/qixiyu/Desktop/pinceau-vue/src/components/button/button.vue?vue&type=style&index=0&lang.postcss:3:1: Unknown word
    at Input.error (C:\Users\qixiyu\Desktop\pinceau-vue\node_modules\.pnpm\postcss@8.4.17\node_modules\postcss\lib\input.js:148:16)
    at Parser.unknownWord (C:\Users\qixiyu\Desktop\pinceau-vue\node_modules\.pnpm\postcss@8.4.17\node_modules\postcss\lib\parser.js:540:22)
    at Parser.other (C:\Users\qixiyu\Desktop\pinceau-vue\node_modules\.pnpm\postcss@8.4.17\node_modules\postcss\lib\parser.js:164:12)
    at Parser.parse (C:\Users\qixiyu\Desktop\pinceau-vue\node_modules\.pnpm\postcss@8.4.17\node_modules\postcss\lib\parser.js:72:16)
    at parse (C:\Users\qixiyu\Desktop\pinceau-vue\node_modules\.pnpm\postcss@8.4.17\node_modules\postcss\lib\parse.js:11:12)
    at new LazyResult (C:\Users\qixiyu\Desktop\pinceau-vue\node_modules\.pnpm\postcss@8.4.17\node_modules\postcss\lib\lazy-result.js:133:16)
    at Processor.process (C:\Users\qixiyu\Desktop\pinceau-vue\node_modules\.pnpm\postcss@8.4.17\node_modules\postcss\lib\processor.js:28:14)
    at compileCSS (file:///C:/Users/qixiyu/Desktop/pinceau-vue/node_modules/.pnpm/vite@3.1.4/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:44546:14)
    at async Object.transform (file:///C:/Users/qixiyu/Desktop/pinceau-vue/node_modules/.pnpm/vite@3.1.4/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:44047:55)
    at async transform (file:///C:/Users/qixiyu/Desktop/pinceau-vue/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:21928:16)
 ELIFECYCLE  Command failed with exit code 1.
```

Example repository address https://github.com/SGAMERyu/pinceau-vue

**Comment by SGAMERyu** [comment]
The require syntax in ast.ts causes vite compilation failure

**Comment by Tahul** [comment]
Thank you so much for the PR! 🙏
